#!/bin/bash

HOSTNAME=$(hostname)
export MY_HOSTNAME=$HOSTNAME

export MY_RANK=${PMIX_RANK}
export MY_NODE=${PALS_NODEID}
export MY_LOCAL_RANK=${PALS_LOCAL_RANKID}

export ONEAPI_DEVICE_SELECTOR=level_zero:$(( $MY_LOCAL_RANK % 4 ))

echo "HOSTNAME: $MY_HOSTNAME" "RANK: $MY_RANK" "NODE: $MY_NODE" "LOCAL_RANK: $MY_LOCAL_RANK" "ONEAPI_DEVICE_SELECTOR: $ONEAPI_DEVICE_SELECTOR"

$@